### PR TITLE
Add React v15 support

### PR DESCRIPTION
**Pull request by detj**
Adds React v15 support using `data-reactroot` alongside the previous `data-react-id`. Although, this can't highlight each of the components by design, at least this enhances the extension to support and highlight root React components.

### CODE REVIEW

**Comment by cymen** [comment]
Looks good -- I've switched laptops but I'll get this built and uploaded to chrome store soon.

**Comment by cymen** [comment]
I released version 1.1 with your change. It may take up to 60 minutes from now to appear in the Chrome Web Store.

**Comment by cymen** [comment]
Oh, and thanks!

**Comment by detj** [comment]
Awesome, thanks!

**Pull request merged**
